# Generated by Django 6.0.7 on 2026-09-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaccount',
            name='webhook_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
