# Generated by Django 6.0.7 on 2026-07-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('remediation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='remediation',
            name='remediation_status_79f9f1_idx',
        ),
        migrations.AddField(
            model_name='remediation',
            name='content_hash',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='remediation',
            index=models.Index(fields=['service_account', 'content_hash'], name='remediation_service_59e6a3_idx'),
        ),
    ]
