# Generated by Django 6.0.7 on 2026-07-29 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remediation', '0002_remove_remediation_remediation_status_79f9f1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemediationArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('vera_precheck', 'Vera precheck'), ('ocr', 'OCR'), ('finalize_tags', 'Finalize tags'), ('alt_text', 'Alt text'), ('link_tag', 'Link tag'), ('vera_postcheck', 'Vera postcheck')], max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=20)),
                ('output_uri', models.CharField(blank=True, max_length=500)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remediation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='remediation.remediation')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('remediation', 'step'), name='one_artifact_per_step')],
            },
        ),
    ]
