# Generated by Django 6.0.7 on 2026-07-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remediation', '0003_remediationartifact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remediationartifact',
            name='step',
            field=models.CharField(choices=[('precheck', 'Precheck'), ('ocr', 'OCR'), ('finalize_tags', 'Finalize tags'), ('alt_text', 'Alt text'), ('link_tag', 'Link tag'), ('postcheck', 'Postcheck')], max_length=20),
        ),
    ]
