# Generated by Django 6.0.7 on 2026-07-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remediation', '0004_alter_remediationartifact_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='remediation',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
