# Generated by Django 6.0.7 on 2026-07-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remediation', '0005_remediation_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remediationartifact',
            name='step',
            field=models.CharField(choices=[('precheck', 'Precheck'), ('ocr', 'OCR'), ('build_tags', 'Build tags'), ('finalize_metadata', 'Finalize metadata'), ('alt_text', 'Alt text'), ('link_tag', 'Link tag'), ('postcheck', 'Postcheck')], max_length=20),
        ),
    ]
