# Generated by Django 6.0.7 on 2026-08-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remediation', '0006_alter_remediationartifact_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remediationartifact',
            name='step',
            field=models.CharField(choices=[('precheck', 'Precheck'), ('ocr', 'OCR'), ('finalize_metadata', 'Finalize metadata'), ('alt_text', 'Alt text'), ('link_tag', 'Link tag'), ('postcheck', 'Postcheck')], max_length=20),
        ),
    ]
