# Generated by Django 6.0.7 on 2026-09-09 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remediation', '0008_alter_remediationartifact_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remediationartifact',
            name='step',
            field=models.CharField(choices=[('precheck', 'Precheck'), ('ocr', 'OCR'), ('font_repair', 'Font repair'), ('finalize_metadata', 'Finalize metadata'), ('link_tag', 'Link tag'), ('alt_text', 'Alt text'), ('scoring', 'Scoring'), ('postcheck', 'Postcheck')], max_length=20),
        ),
        migrations.CreateModel(
            name='RemediationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1)),
                ('manual_review_items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remediation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='remediation.remediation')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('precheck', 'Precheck'), ('ocr', 'OCR'), ('font_repair', 'Font repair'), ('finalize_metadata', 'Finalize metadata'), ('link_tag', 'Link tag'), ('alt_text', 'Alt text'), ('scoring', 'Scoring'), ('postcheck', 'Postcheck')], max_length=20)),
                ('is_compliant', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remediation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_results', to='remediation.remediation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('remediation', 'step'), name='one_verification_result_per_step')],
            },
        ),
    ]
