# Generated by Django 6.0.7 on 2026-09-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remediation', '0009_alter_remediationartifact_step_remediationscore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationresult',
            name='failed_rules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='verificationresult',
            name='verapdf_version',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
