# Generated by Django 6.0.7 on 2026-09-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remediation', '0010_verificationresult_failed_rules_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retry_floor_version', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='remediation',
            name='pipeline_version',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
