# Generated by Django 6.0.7 on 2026-09-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remediation', '0011_pipelineconfig_remediation_pipeline_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='remediation',
            name='final_output_uri',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
