# Generated by Django 6.0.7 on 2026-09-16 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remediation', '0012_remediation_final_output_uri'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemediationCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remediation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='remediation.remediation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('remediation', 'callback_url'), name='one_callback_per_url_per_remediation')],
            },
        ),
    ]
